import Head from "next/head";
import Image from "next/image";
import Contact from "../components/contact/contact";
import styles from "../styles/Home.module.css";
import React,{useState} from "react";

export default function Home({initialContacts}) {
  const [contacts, setContacts] = useState(initialContacts)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex bg-gray-400 h-screen">
        <div className=" w-2/5 h-3/5">
          <label class="block">
            <input
              type="firstname"
              name="firstname"
              class=" ml-5 w-96 h-20 text-slate-700  mt-5 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block  rounded-md sm:text-sm focus:ring-1"
              placeholder="Firstname"
            />
          </label>
          <label class="block">
            <input
              type="lastname"
              name="lastname"
              class=" ml-5 w-96 h-20 text-slate-700  mt-5 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block  rounded-md sm:text-sm focus:ring-1"
              placeholder="Lastname"
            />
          </label>
          <label class="block">
            <input
              type="email"
              name="email"
              class=" ml-5 w-96 h-20 text-slate-700  mt-5 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block  rounded-md sm:text-sm focus:ring-1"
              placeholder="Email"
            />
          </label>
          <label class="block">
            <input
              type="avatar"
              name="avatar"
              class=" ml-5 w-96 h-20 text-slate-700  mt-5 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block  rounded-md sm:text-sm focus:ring-1"
              placeholder="Avatar"
            />
          </label>
        </div>
        <div class="bg-blue-400 w-4/5">
        <ul role="list" class="p-6 divide-y divide-slate-200">
          {
            contacts.map((contact)=>{
              return(
                <Contact person={contact} />
              )
            })
          }
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  let contacts = [
    {
      id: "1",
      firstname: "Marc",
      lastname: "Kruiß",
      email: "k.marc@a1.net",
      avatar: "https://github.com/Marc-Kruiss.png",
    },
    {
      id: "2",
      firstname: "Patrick",
      lastname: "Kruiß",
      email: "k.marc@a1.net",
      avatar: "https://github.com/Marc-Kruiss.png",
    },
  ];

  return {
    props: {
      initialContacts: contacts,
    },
  };
}